### ISSUE TITLE
Release 2.1.3

### ISSUE THREAD

**Issue by kliem** [sagemath/cypari2#121] opened 2022-10-08 19:28 UTC
@videlec Apparently you are the only active maintainer with access to pypi. Would be great, if you share that with someone.

The release 2.1.2 has lots of helper files along. I don't know exactly, how all of that got generated.

I think we have a good improvement for release 2.1.3 by supporting python 3.11 and we are not aware of any regressions (and apparently we support recent PARI versions, just that there is a failing test because of a bug).

**Comment by tornaria** [comment] 2022-10-30 18:48
@kliem could you tag 2.1.3 here in the github repo? At least we can get a source tarball from github, if not from pypi.

**Comment by videlec** [comment] 2022-11-10 10:13
Why did the version bump was merged in master in the first place!?

**Comment by videlec** [comment] 2022-11-10 10:22
Thanks to your activity, we now have plenty of version bumps appearing even inside merge commits. These are not tagged properly contratrily to all versionning that appeared before. Given this, I don't see why I would grant access rights to this repo rather than restricting it.
```
$ git log VERSION
commit e10755333838d18fb28fbc9860e3ae780f5f02d2 (origin/use_cysignals_hook)
Merge: f8cb330 002739f
Author: Dima Pasechnik <dima@pasechnik.info>
Date:   Wed Nov 2 14:00:14 2022 +0000

    Merge branch 'master' into use_cysignals_hook

commit 34198a78e86ba6ba684b25ae5ebb3e1a4e54c19f
Author: Jonathan Kliem <jonathan.kliem@fu-berlin.de>
Date:   Mon Oct 3 10:08:45 2022 +0200

    bump version

commit f8cb3306639e4c45612f988866efc73bec1e9bb4
Author: Jonathan Kliem <jonathan.kliem@fu-berlin.de>
Date:   Thu Jun 2 14:43:28 2022 +0200

    bump version

commit d1fd6ca09b9f6fafbf8b084613f88950a11e745e (tag: 2.1.2)
Author: Vincent Delecroix <vincent.delecroix@u-bordeaux.fr>
Date:   Sat Nov 7 08:43:44 2020 +0100

    Version 2.1.2

commit 03c41c57bff6a73a2b216d9997115ee629c2562c (tag: 2.1.2b1)
Author: Vincent Delecroix <vincent.delecroix@u-bordeaux.fr>
Date:   Sun Nov 1 19:52:56 2020 +0100

    Version 2.1.2b1

commit 7bf42118a6df470ae67fae6d403a0f0796c17355 (tag: 2.1.1)
Author: Jeroen Demeyer <J.Demeyer@UGent.be>
Date:   Tue Apr 23 12:57:51 2019 +0200

    Version 2.1.1
```

**Comment by videlec** [comment] 2022-11-10 10:41
I will rewrite the git history and make a release afterwards.

**Comment by videlec** [comment] 2022-11-10 10:58
I am aware of one regression : cypari2 does not compile with cysignals 1.11.2 which is the latest version available on PyPI.

**Comment by tornaria** [comment] 2022-11-10 11:12
> I am aware of one regression : cypari2 does not compile with cysignals 1.11.2 which is the latest version available on PyPI.

It is compiling ok for us on void linux (cysignals 1.11.2 from pypi, cypari2 "2.1.3" from 34198a78e86ba6ba684b25ae5ebb3e1a4e54c19f).

**Comment by videlec** [comment] 2022-11-10 11:32
The problem is #125. It will be solved my history rewrite.

**Comment by mkoeppe** [comment] 2023-10-04 19:12
As 2.1.3 is tagged and on https://pypi.org/project/cypari2/#history, I am closing this issue.

**Closed by mkoeppe** 2023-10-04 19:12 UTC
